-- CreateEnum
CREATE TYPE "SECTION_TYPE" AS ENUM ('HERO', 'PROMOTIONAL', 'BENEFITS', 'NEW_ARRIVALS');

-- AlterTable
ALTER TABLE "Section" ADD COLUMN     "type" "SECTION_TYPE" NOT NULL DEFAULT 'HERO';
